### ISSUE TITLE
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface ISession

### ISSUE THREAD

**Issue by channone-arif-nbcuni** [monetate/ectou-export#5]
I am seeing this error. Is this method to tied to a specific version of VirtualBox?

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'channone-updated'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: VirtualBoxVMs_default_1470428077630_77376
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "2f81713a-b5dd-4832-b53d-bee83abcd845", "--type", "headless"]

Stderr: VBoxManage: error: The VM session was aborted
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface ISession

**Comment by dualviolet** [comment]
I use sierra on MBPR.

I have your issue same.
My error environment is below.

1) vbox export from ubuntu/yaketty64 of windows 10 host.
2) its import virtualbox on Mac sierra.
3) I run command 'vagrant box add --name [VM name] [exported vagrant box filename]'
4) and 'vagrant up [VM name] --provider virtualbox
5) I meet same your error.

My resolve action below.

Base proceed with 1), 2), 3), 4)
5) Run VirtualBox Manager
6) select[VM name]
7) Settings
8) 'System' tab > Motherboard > Boor Order > [ ] Floppy (uncheck)
9) 'Audiot' tab > [ ] Enable Audio (uncheck)
10) 'Ports' tab >  [ ] Enable Serial Port (uncheck)
11) OK
12) again 'vagrant up [VM name] --provider virtualbox

lately
Good Luch
